---
repos:
  - repo: local
    hooks:
      # Format Nix files with the formatter.
      - id: nixfmt
        name: Format Nix files
        language: system
        entry: nix fmt
        files: .*\.nix$
