---
repos:
  - repo: local
    hooks:
      # Format Nix files with the formatter.
      - id: nixfmt
        name: Format Nix files
        language: system
        entry: nix fmt
        files: .*\.nix$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
