[tool.ruff.lint]
select = ["ALL"]
extend-ignore = [
  # `one-blank-line-before-class` (D203) and `no-blank-line-before-class`
  # (D211) are incompatible. Ignoring `one-blank-line-before-class`.
  "D203",

  # `multi-line-summary-first-line` (D212) and
  # `multi-line-summary-second-line` (D213) are incompatible. Ignoring
  # `multi-line-summary-second-line`.
  "D213",

  # The following rules may cause conflicts when used with the formatter:
  "COM812",
  "ISC001",
]
